apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nhl4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-nhl4
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-nhl4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nhl4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nhl4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xqxt-tenant/quarkus/devfile-sample-code-with-quarkus-nhl4@sha256:28eb576eadf5d8cbae8523305b8534603f902c97b97adc54b7e720e94ba83767
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
